
library(dashboardthemes)
library(dplyr)
library(stringr)
library(lubridate)
library(tidyr)
library(plotly)
library(shiny)
library(shinythemes)
library(shinydashboard)

library(ghyp)
library(ggplot2)
library(dplyr)
library(rlang)
library(purrr)
library(tidyr)
library(formattable)

library(lubridate)
#library(rayshader)
#library(d3heatmap)
library(tidyquant)
library(quantmod)
library(DT)

library(plotly)






######

ui <- dashboardPage(

                    
                    
                    
  dashboardHeader(title = "Live Portfolio Optimization in R", titleWidth = 350),
  dashboardSidebar(theme_purple_gradient, width=250,
    
     
              
    
    sliderInput('riskfree', 'Risk-Free Rate:',
                min = 0, max = .002, value = .001),
    checkboxGroupInput("variable", "Portfolio Stock Options:", inline = F, 
                       selected = c('ABT'='ABT',
                                    'ABBV'='ABBV',
                                    'ABMD'='ABMD',
                                    'ACN'='ACN'),
                       c('ABT'='ABT',
                         'ABBV'='ABBV',
                         'ABMD'='ABMD',
                         'ACN'='ACN',
                         'ATVI'='ATVI',
                         'ADBE'='ADBE',
                         'AMD'='AMD',
                         'AAP'='AAP',
                         'AES'='AES',
                         'AFL'='AFL',
                         'A'='A',
                         'APD'='APD',
                         'AKAM'='AKAM',
                         'ALK'='ALK',
                         'ALB'='ALB',
                         'ARE'='ARE',
                         'ALXN'='ALXN',
                         'ALGN'='ALGN',
                         'ALLE'='ALLE',
                         'ADS'='ADS',
                         'LNT'='LNT',
                         'ALL'='ALL',
                         'GOOGL'='GOOGL',
                         'GOOG'='GOOG',
                         'MO'='MO',
                         'AMZN'='AMZN',
                         'AMCR'='AMCR',
                         'AEE'='AEE',
                         'AAL'='AAL',
                         'AEP'='AEP',
                         'AXP'='AXP',
                         'AIG'='AIG',
                         'AMT'='AMT',
                         'AWK'='AWK',
                         'AMP'='AMP',
                         'ABC'='ABC',
                         'AME'='AME',
                         'AMGN'='AMGN',
                         'APH'='APH',
                         'ADI'='ADI',
                         'ANSS'='ANSS',
                         'ANTM'='ANTM',
                         'AON'='AON',
                         'AOS'='AOS',
                         'APA'='APA',
                         'AIV'='AIV',
                         'AAPL'='AAPL',
                         'AMAT'='AMAT',
                         'APTV'='APTV',
                         'ADM'='ADM',
                         'ANET'='ANET',
                         'AJG'='AJG',
                         'AIZ'='AIZ',
                         'T'='T',
                         'ATO'='ATO',
                         'ADSK'='ADSK',
                         'ADP'='ADP',
                         'AZO'='AZO',
                         'AVB'='AVB',
                         'AVY'='AVY',
                         'BKR'='BKR',
                         'BLL'='BLL',
                         'BAC'='BAC',
                         'BK'='BK',
                         'BAX'='BAX',
                         'BDX'='BDX',
                         'BRK.B'='BRK.B',
                         'BBY'='BBY',
                         'BIIB'='BIIB',
                         'BLK'='BLK',
                         'BA'='BA',
                         'BKNG'='BKNG',
                         'BWA'='BWA',
                         'BXP'='BXP',
                         'BSX'='BSX',
                         'BMY'='BMY',
                         'AVGO'='AVGO',
                         'BR'='BR',
                         'BF.B'='BF.B',
                         'CHRW'='CHRW',
                         'COG'='COG',
                         'CDNS'='CDNS',
                         'CPB'='CPB',
                         'COF'='COF',
                         'CAH'='CAH',
                         'KMX'='KMX',
                         'CCL'='CCL',
                         'CARR'='CARR',
                         'CAT'='CAT',
                         'CBOE'='CBOE',
                         'CBRE'='CBRE',
                         'CDW'='CDW',
                         'CE'='CE',
                         'CNC'='CNC',
                         'CNP'='CNP',
                         'CTL'='CTL',
                         'CERN'='CERN',
                         'CF'='CF',
                         'SCHW'='SCHW',
                         'CHTR'='CHTR',
                         'CVX'='CVX',
                         'CMG'='CMG',
                         'CB'='CB',
                         'CHD'='CHD',
                         'CI'='CI',
                         'CINF'='CINF',
                         'CTAS'='CTAS',
                         'CSCO'='CSCO',
                         'C'='C',
                         'CFG'='CFG',
                         'CTXS'='CTXS',
                         'CLX'='CLX',
                         'CME'='CME',
                         'CMS'='CMS',
                         'KO'='KO',
                         'CTSH'='CTSH',
                         'CL'='CL',
                         'CMCSA'='CMCSA',
                         'CMA'='CMA',
                         'CAG'='CAG',
                         'CXO'='CXO',
                         'COP'='COP',
                         'ED'='ED',
                         'STZ'='STZ',
                         'COO'='COO',
                         'CPRT'='CPRT',
                         'GLW'='GLW',
                         'CTVA'='CTVA',
                         'COST'='COST',
                         'COTY'='COTY',
                         'CCI'='CCI',
                         'CSX'='CSX',
                         'CMI'='CMI',
                         'CVS'='CVS',
                         'DHI'='DHI',
                         'DHR'='DHR',
                         'DRI'='DRI',
                         'DVA'='DVA',
                         'DE'='DE',
                         'DAL'='DAL',
                         'XRAY'='XRAY',
                         'DVN'='DVN',
                         'DXCM'='DXCM',
                         'FANG'='FANG',
                         'DLR'='DLR',
                         'DFS'='DFS',
                         'DISCA'='DISCA',
                         'DISCK'='DISCK',
                         'DISH'='DISH',
                         'DG'='DG',
                         'DLTR'='DLTR',
                         'D'='D',
                         'DPZ'='DPZ',
                         'DOV'='DOV',
                         'DOW'='DOW',
                         'DTE'='DTE',
                         'DUK'='DUK',
                         'DRE'='DRE',
                         'DD'='DD',
                         'DXC'='DXC',
                         'ETFC'='ETFC',
                         'EMN'='EMN',
                         'ETN'='ETN',
                         'EBAY'='EBAY',
                         'ECL'='ECL',
                         'EIX'='EIX',
                         'EW'='EW',
                         'EA'='EA',
                         'EMR'='EMR',
                         'ETR'='ETR',
                         'EOG'='EOG',
                         'EFX'='EFX',
                         'EQIX'='EQIX',
                         'EQR'='EQR',
                         'ESS'='ESS',
                         'EL'='EL',
                         'EVRG'='EVRG',
                         'ES'='ES',
                         'RE'='RE',
                         'EXC'='EXC',
                         'EXPE'='EXPE',
                         'EXPD'='EXPD',
                         'EXR'='EXR',
                         'XOM'='XOM',
                         'FFIV'='FFIV',
                         'FB'='FB',
                         'FAST'='FAST',
                         'FRT'='FRT',
                         'FDX'='FDX',
                         'FIS'='FIS',
                         'FITB'='FITB',
                         'FE'='FE',
                         'FRC'='FRC',
                         'FISV'='FISV',
                         'FLT'='FLT',
                         'FLIR'='FLIR',
                         'FLS'='FLS',
                         'FMC'='FMC',
                         'F'='F',
                         'FTNT'='FTNT',
                         'FTV'='FTV',
                         'FBHS'='FBHS',
                         'FOXA'='FOXA',
                         'FOX'='FOX',
                         'BEN'='BEN',
                         'FCX'='FCX',
                         'GPS'='GPS',
                         'GRMN'='GRMN',
                         'IT'='IT',
                         'GD'='GD',
                         'GE'='GE',
                         'GIS'='GIS',
                         'GM'='GM',
                         'GPC'='GPC',
                         'GILD'='GILD',
                         'GL'='GL',
                         'GPN'='GPN',
                         'GS'='GS',
                         'GWW'='GWW',
                         'HRB'='HRB',
                         'HAL'='HAL',
                         'HBI'='HBI',
                         'HOG'='HOG',
                         'HIG'='HIG',
                         'HAS'='HAS',
                         'HCA'='HCA',
                         'PEAK'='PEAK',
                         'HSIC'='HSIC',
                         'HSY'='HSY',
                         'HES'='HES',
                         'HPE'='HPE',
                         'HLT'='HLT',
                         'HFC'='HFC',
                         'HOLX'='HOLX',
                         'HD'='HD',
                         'HON'='HON',
                         'HRL'='HRL',
                         'HST'='HST',
                         'HWM'='HWM',
                         'HPQ'='HPQ',
                         'HUM'='HUM',
                         'HBAN'='HBAN',
                         'HII'='HII',
                         'IEX'='IEX',
                         'IDXX'='IDXX',
                         'INFO'='INFO',
                         'ITW'='ITW',
                         'ILMN'='ILMN',
                         'INCY'='INCY',
                         'IR'='IR',
                         'INTC'='INTC',
                         'ICE'='ICE',
                         'IBM'='IBM',
                         'IP'='IP',
                         'IPG'='IPG',
                         'IFF'='IFF',
                         'INTU'='INTU',
                         'ISRG'='ISRG',
                         'IVZ'='IVZ',
                         'IPGP'='IPGP',
                         'IQV'='IQV',
                         'IRM'='IRM',
                         'JKHY'='JKHY',
                         'J'='J',
                         'JBHT'='JBHT',
                         'SJM'='SJM',
                         'JNJ'='JNJ',
                         'JCI'='JCI',
                         'JPM'='JPM',
                         'JNPR'='JNPR',
                         'KSU'='KSU',
                         'K'='K',
                         'KEY'='KEY',
                         'KEYS'='KEYS',
                         'KMB'='KMB',
                         'KIM'='KIM',
                         'KMI'='KMI',
                         'KLAC'='KLAC',
                         'KSS'='KSS',
                         'KHC'='KHC',
                         'KR'='KR',
                         'LB'='LB',
                         'LHX'='LHX',
                         'LH'='LH',
                         'LRCX'='LRCX',
                         'LW'='LW',
                         'LVS'='LVS',
                         'LEG'='LEG',
                         'LDOS'='LDOS',
                         'LEN'='LEN',
                         'LLY'='LLY',
                         'LNC'='LNC',
                         'LIN'='LIN',
                         'LYV'='LYV',
                         'LKQ'='LKQ',
                         'LMT'='LMT',
                         'L'='L',
                         'LOW'='LOW',
                         'LYB'='LYB',
                         'MTB'='MTB',
                         'MRO'='MRO',
                         'MPC'='MPC',
                         'MKTX'='MKTX',
                         'MAR'='MAR',
                         'MMC'='MMC',
                         'MLM'='MLM',
                         'MAS'='MAS',
                         'MA'='MA',
                         'MKC'='MKC',
                         'MXIM'='MXIM',
                         'MCD'='MCD',
                         'MCK'='MCK',
                         'MDT'='MDT',
                         'MRK'='MRK',
                         'MET'='MET',
                         'MTD'='MTD',
                         'MGM'='MGM',
                         'MCHP'='MCHP',
                         'MU'='MU',
                         'MSFT'='MSFT',
                         'MAA'='MAA',
                         'MHK'='MHK',
                         'TAP'='TAP',
                         'MDLZ'='MDLZ',
                         'MNST'='MNST',
                         'MCO'='MCO',
                         'MS'='MS',
                         'MOS'='MOS',
                         'MSI'='MSI',
                         'MSCI'='MSCI',
                         'MYL'='MYL',
                         'NDAQ'='NDAQ',
                         'NOV'='NOV',
                         'NTAP'='NTAP',
                         'NFLX'='NFLX',
                         'NWL'='NWL',
                         'NEM'='NEM',
                         'NWSA'='NWSA',
                         'NWS'='NWS',
                         'NEE'='NEE',
                         'NLSN'='NLSN',
                         'NKE'='NKE',
                         'NI'='NI',
                         'NBL'='NBL',
                         'JWN'='JWN',
                         'NSC'='NSC',
                         'NTRS'='NTRS',
                         'NOC'='NOC',
                         'NLOK'='NLOK',
                         'NCLH'='NCLH',
                         'NRG'='NRG',
                         'NUE'='NUE',
                         'NVDA'='NVDA',
                         'NVR'='NVR',
                         'ORLY'='ORLY',
                         'OXY'='OXY',
                         'ODFL'='ODFL',
                         'OMC'='OMC',
                         'OKE'='OKE',
                         'ORCL'='ORCL',
                         'OTIS'='OTIS',
                         'PCAR'='PCAR',
                         'PKG'='PKG',
                         'PH'='PH',
                         'PAYX'='PAYX',
                         'PAYC'='PAYC',
                         'PYPL'='PYPL',
                         'PNR'='PNR',
                         'PBCT'='PBCT',
                         'PEP'='PEP',
                         'PKI'='PKI',
                         'PRGO'='PRGO',
                         'PFE'='PFE',
                         'PM'='PM',
                         'PSX'='PSX',
                         'PNW'='PNW',
                         'PXD'='PXD',
                         'PNC'='PNC',
                         'PPG'='PPG',
                         'PPL'='PPL',
                         'PFG'='PFG',
                         'PG'='PG',
                         'PGR'='PGR',
                         'PLD'='PLD',
                         'PRU'='PRU',
                         'PEG'='PEG',
                         'PSA'='PSA',
                         'PHM'='PHM',
                         'PVH'='PVH',
                         'QRVO'='QRVO',
                         'PWR'='PWR',
                         'QCOM'='QCOM',
                         'DGX'='DGX',
                         'RL'='RL',
                         'RJF'='RJF',
                         'RTX'='RTX',
                         'O'='O',
                         'REG'='REG',
                         'REGN'='REGN',
                         'RF'='RF',
                         'RSG'='RSG',
                         'RMD'='RMD',
                         'RHI'='RHI',
                         'ROK'='ROK',
                         'ROL'='ROL',
                         'ROP'='ROP',
                         'ROST'='ROST',
                         'RCL'='RCL',
                         'SPGI'='SPGI',
                         'CRM'='CRM',
                         'SBAC'='SBAC',
                         'SLB'='SLB',
                         'STX'='STX',
                         'SEE'='SEE',
                         'SRE'='SRE',
                         'NOW'='NOW',
                         'SHW'='SHW',
                         'SPG'='SPG',
                         'SWKS'='SWKS',
                         'SLG'='SLG',
                         'SNA'='SNA',
                         'SO'='SO',
                         'LUV'='LUV',
                         'SWK'='SWK',
                         'SBUX'='SBUX',
                         'STT'='STT',
                         'STE'='STE',
                         'SYK'='SYK',
                         'SIVB'='SIVB',
                         'SYF'='SYF',
                         'SNPS'='SNPS',
                         'SYY'='SYY',
                         'TMUS'='TMUS',
                         'TROW'='TROW',
                         'TTWO'='TTWO',
                         'TPR'='TPR',
                         'TGT'='TGT',
                         'TEL'='TEL',
                         'FTI'='FTI',
                         'TFX'='TFX',
                         'TXN'='TXN',
                         'TXT'='TXT',
                         'TMO'='TMO',
                         'TIF'='TIF',
                         'TJX'='TJX',
                         'TSCO'='TSCO',
                         'TT'='TT',
                         'TDG'='TDG',
                         'TRV'='TRV',
                         'TFC'='TFC',
                         'TWTR'='TWTR',
                         'TSN'='TSN',
                         'UDR'='UDR',
                         'ULTA'='ULTA',
                         'USB'='USB',
                         'UAA'='UAA',
                         'UA'='UA',
                         'UNP'='UNP',
                         'UAL'='UAL',
                         'UNH'='UNH',
                         'UPS'='UPS',
                         'URI'='URI',
                         'UHS'='UHS',
                         'UNM'='UNM',
                         'VFC'='VFC',
                         'VLO'='VLO',
                         'VAR'='VAR',
                         'VTR'='VTR',
                         'VRSN'='VRSN',
                         'VRSK'='VRSK',
                         'VZ'='VZ',
                         'VRTX'='VRTX',
                         'VIAC'='VIAC',
                         'V'='V',
                         'VNO'='VNO',
                         'VMC'='VMC',
                         'WRB'='WRB',
                         'WAB'='WAB',
                         'WMT'='WMT',
                         'WBA'='WBA',
                         'DIS'='DIS',
                         'WM'='WM',
                         'WAT'='WAT',
                         'WEC'='WEC',
                         'WFC'='WFC',
                         'WELL'='WELL',
                         'WST'='WST',
                         'WDC'='WDC',
                         'WU'='WU',
                         'WRK'='WRK',
                         'WY'='WY',
                         'WHR'='WHR',
                         'WMB'='WMB',
                         'WLTW'='WLTW',
                         'WYNN'='WYNN',
                         'XEL'='XEL',
                         'XRX'='XRX',
                         'XLNX'='XLNX',
                         'XYL'='XYL',
                         'YUM'='YUM',
                         'ZBRA'='ZBRA',
                         'ZBH'='ZBH',
                         'ZION'='ZION',
                         'ZTS'='ZTS'
                         
                         
                         
                         
                         
                         
                         ))
  
   
    
    
 
    
    ),
  
  
  

  
  
  dashboardBody(theme_purple_gradient, 
 
    fluidRow(
                 valueBoxOutput("minbox"),
                  valueBoxOutput("riskfreebox"),
                 valueBoxOutput("max")
                  
               )
    ,
  
    fluidRow(box(title="Optimal Weights", width=100,
      
            formattableOutput("table1", width="85%")))
    ,
 
   

    
    fluidRow(
    
    tabsetPanel(type = "tabs",
                tabPanel("Historic Returns", formattableOutput("table2", width="75%")),
                tabPanel("Historic Prices", plotlyOutput("plot1", width="75%")),
                
               tabPanel("Downloads",  
                        downloadButton("downloadData2", "Historical Returns") )
    )
    
    )
    

  ) 
  
)







